version: '3'

services:
  db:
    restart: always
    image: postgres:11
    volumes:
      - mothra_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432
  web:
    restart: always
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"

volumes:
  mothra_data:
