# Generated by Django 2.2.6 on 2019-10-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_orgtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(null=True)),
                ('grades', models.ManyToManyField(to='accounts.Grade')),
                ('locations', models.ManyToManyField(to='accounts.Location')),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.OrgType')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
