# Generated by Django 2.2.6 on 2019-11-05 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_seed_org_type'),
        ('inventory', '0004_usagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_push', models.BooleanField()),
                ('how_push', models.TextField()),
                ('can_pull', models.BooleanField()),
                ('how_pull', models.TextField()),
                ('is_deprecated', models.BooleanField()),
                ('when_deprecated', models.DateField(default=datetime.date.today)),
                ('why_deprecated', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.UsageType')),
            ],
            options={
                'ordering': ('product', 'organization'),
            },
        ),
    ]
