# Generated by Django 2.2.6 on 2019-11-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='when_deprecated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
