# Generated by Django 2.2.6 on 2019-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20191106_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='how_pull',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='how_push',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='why_deprecated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
