# Generated by Django 2.2.6 on 2020-02-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20191106_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Subject'),
        ),
    ]
