# Generated by Django 3.0.3 on 2020-02-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200208_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='usage',
            name='can_pull',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='can_push',
        ),
        migrations.AlterField(
            model_name='usage',
            name='how_pull',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pull_type', to='inventory.DataInterface'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='how_push',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='push_type', to='inventory.DataInterface'),
        ),
    ]
