# Generated by Django 3.0.3 on 2020-02-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_domain_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='fas fa-brain', max_length=50),
        ),
    ]
